### ISSUE TITLE
Visualisierung der gegnerischen Schwarmgröße

### ISSUE THREAD

**Issue by fl-oe** [foxytocin/FishAreFriends#61]
Visualisierung der gegnerischen Schwarmgröße

**Comment by foxytocin** [comment]
"ForceFields"

z.B.
- Entfernung Player / Gegner < 10 >> forceField mit Playerfarbe (damit man weiß wer da ist?)
- Entfernung Player / Gegner < 5 >> forceField des Players / AI-Player in den Farben:
  - rot: wenn man schwächer ist
  - orange: wenn der Ausgang des Kampfes ungewiss ist
  - grün: wenn man Gefahrlos angreifen kann

**Comment by foxytocin** [comment]
Wird zu Gunsten eines neuen Systems geschlossen.

Siehe >> #63
