### ISSUE TITLE
Jagdverhalten des Predator anpassen

### ISSUE THREAD

**Issue by foxytocin** [foxytocin/FishAreFriends#62]
#### aktuell:
  - Hai macht Jagt auf Boids (die ihn sehen)
  - Hai greift keine Schwärme gezielt an

#### angestrebt:
  - Hai macht Jagt auf Schwärme (Spieler und AI-Spieler)
  - Spieler wird "gezwungen" die Nähe zum Hai zu vermeiden (damit sein Schwarm nicht gefressen wird)

**Comment by fl-oe** [comment]
PR #64
