### ISSUE TITLE
AI-Player bleiben beim Angriff "ineinander" stecken

### ISSUE THREAD

**Issue by foxytocin** [foxytocin/FishAreFriends#66]
- befinden sich zwei AI-Player im Kampf, zeigt der Angegriffene kein Fluchtverhalten. Statt dessen schwimmen sie ineinander / miteinander umher.
- Vermuteter Bug: Angriffsverhalten wechselt zwischen beiden abwechselnd hin und her

#### Vorschlag
- es wird ein timeout gebraucht, damit der angegriffene nicht direkt zurückschlagen kann

**Comment by fl-oe** [comment]
#71
